from django.db import models

# Create your models here.
class Municipio(models.Model):
    nombre = models.CharField(max_length=100)
    latitud = models.FloatField(blank=True, null=True)
    longitud = models.FloatField(blank=True, null=True)
    LeticiaConexion = models.FloatField(blank=True, null=True)
    MedellinConexion = models.FloatField(blank=True, null=True)
    AraucaConexion = models.FloatField(blank=True, null=True)
    BarranquillaConexion = models.FloatField(blank=True, null=True)
    BogotaConexion = models.FloatField(blank=True, null=True)
    CartagenaConexion = models.FloatField(blank=True, null=True)
    TunjaConexion = models.FloatField(blank=True, null=True)
    ManizalesConexion = models.FloatField(blank=True, null=True)
    MituConexion = models.FloatField(blank=True, null=True)
    YopalConexion = models.FloatField(blank=True, null=True)
    PopayanConexion = models.FloatField(blank=True, null=True)
    ValleduparConexion = models.FloatField(blank=True, null=True)
    QuibdoConexion = models.FloatField(blank=True, null=True)
    MonteriaConexion = models.FloatField(blank=True, null=True)
    IniridaConexion = models.FloatField(blank=True, null=True)
    RiohachaConexion = models.FloatField(blank=True, null=True)
    SanJoseDelGuaviareConexion = models.FloatField(blank=True, null=True)
    NeivaConexion = models.FloatField(blank=True, null=True)
    SantaMartaConexion = models.FloatField(blank=True, null=True)
    VillavicencioConexion = models.FloatField(blank=True, null=True)
    PastoConexion = models.FloatField(blank=True, null=True)
    CucutaConexion = models.FloatField(blank=True, null=True)
    SantaRitaConexion = models.FloatField(blank=True, null=True)
    ArmeniaConexion = models.FloatField(blank=True, null=True)
    UnionConexion = models.FloatField(blank=True, null=True)
    BucaramangaConexion = models.FloatField(blank=True, null=True)
    SincelejoConexion = models.FloatField(blank=True, null=True)
    PuertoTrujilloConexion = models.FloatField(blank=True, null=True)
    CaliConexion = models.FloatField(blank=True, null=True)
    PuertoCarrenoConexion = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.nombre