export interface Municipio {
    id:                         number;
    nombre:                     string;
    latitud:                    number;
    longitud:                   number;
    LeticiaConexion:            number;
    MedellinConexion:           number;
    AraucaConexion:             number;
    BarranquillaConexion:       number;
    BogotaConexion:             number;
    CartagenaConexion:          number;
    TunjaConexion:              number;
    ManizalesConexion:          number;
    MituConexion:               number;
    YopalConexion:              number;
    PopayanConexion:            number;
    ValleduparConexion:         number;
    QuibdoConexion:             number;
    MonteriaConexion:           number;
    IniridaConexion:            number;
    RiohachaConexion:           number;
    SanJosedelGuaviareConexion: number;
    NeivaConexion:              number;
    SantaMartaConexion:         number;
    VillavicencioConexion:      number;
    PastoConexion:              number;
    CucutaConexion:             number;
    SantaRitaConexion:          number;
    ArmeniaConexion:            number;
    UnionConexion:              number;
    BucaramangaConexion:        number;
    SincelejoConexion:          number;
    PuertoTrujilloConexion:     number;
    CaliConexion:               number;
    PuertoCarrenoConexion:      number;
    [key: string]: any;
}