# Generated by Django 5.1 on 2024-08-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='habitantes',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='superficie',
        ),
    ]
