# Generated by Django 5.1 on 2024-09-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0002_remove_municipio_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='AraucaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='ArmeniaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='BarranquillaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='BogotaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='BucaramangaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='CaliConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='CartagenaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='CucutaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='IniridaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='LeticiaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='ManizalesConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='MedellinConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='MituConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='MonteriaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='NeivaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='PastoConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='PopayanConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='PuertoCarrenoConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='PuertoTrujilloConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='QuibdoConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='RiohachaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='SanJoseDelGuaviareConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='SantaMartaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='SantaRitaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='SincelejoConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='UnionConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='ValleduparConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='VillavicencioConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='YopalConexion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
