# Generated by Django 5.1 on 2024-09-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0003_municipio_araucaconexion_municipio_armeniaconexion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='TunjaConexion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
