# Generated by Django 5.1 on 2024-09-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0004_municipio_tunjaconexion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='SanJoseDelGuaviareConexion',
            new_name='SanJosedelGuaviareConexion',
        ),
    ]
